//
//  AnalyticsConstants.swift
//  FarmerChat
//
//  Event names, Adjust tokens, screen names, property keys, and user attribute keys
//  per ANALYTICS_EVENTS_AND_ATTRIBUTES_BY_SCREEN.md. Do not change case or add new keys.
//

import Foundation

enum AnalyticsConstants {

    // MARK: - Screen names (exact from doc)
    enum Screen {
        static let splashScreen = "Splash Screen"
        static let selectLanguageScreen = "Select Language Screen"
        static let enterNameScreen = "Enter Name Screen"
        static let dashboardScreen = "Dashboard Screen"
        static let chatScreen = "Chat Screen"
        static let settingsScreen = "Settings Screen"
        static let helpAndSupportScreen = "Help & Support Screen"
        static let helpAndSupportScreenAlt = "Help and support screen"
        static let chatHistoryScreen = "Chat History screen"
        static let loginScreen = "Login Screen"
        static let verifyOTPScreen = "Verify OTP Screen"
        static let selectCountryScreen = "Select Country Screen"
        static let gpsScreen = "GPS Screen"
        static let menu = "Menu"
        static let sideMenu = "Side Menu"
    }

    // MARK: - Event names (exact from doc)
    enum Event {
        static let appInstalled = "App_Installed"
        static let appUpdated = "App_Updated"
        static let appOpened = "App_Opened"
        static let screenViewed = "Screen_Viewed"
        static let screenExited = "Screen_Exited"
        static let termsOfUseOpened = "terms_of_use_opened"
        static let privacyPolicyOpened = "privacy_policy_opened"
        static let saveLanguageClickEvent = "Save_Language_Click_Event"
        static let nameSaveClickEvent = "Name_Save_Click_Event"
        static let nameSkipClickEvent = "Name_Skip_Click_Event"
        static let firstTimeDashboardViewed = "FirstTimeDashboardViewed"
        static let dashboardViewed = "Dashboard_Viewed"
        static let cardShown = "Card_Shown"
        static let cardViewed = "Card_Viewed"
        static let cardClicked = "Card_Clicked"
        static let hamburgerMenuClicked = "Hamburger_Menu_Clicked"
        static let weatherForecastViewed = "Weather_Forecast_Viewed"
        static let chatIconClicked = "Chat_Icon_Clicked"
        static let microphoneClickEvent = "Microphone_Click_Event"
        static let imageOptionDialogClickEvent = "Image_Option_Dialog_Click_Event"
        static let permissionPopupShown = "Permission_popup_shown"
        static let permissionGranted = "Permission_granted"
        static let permissionDenied = "Permission_denied"
        static let inputCaptureFailed = "Input_Capture_Failed"
        static let contentTryAgainClicked = "Content_Try_Again_Clicked"
        static let apiCallInitiated = "API_Call_Initiated"
        static let apiCallSuccess = "API_Call_Success"
        static let apiCallFailed = "API_Call_Failed"
        static let apiCallTimeout = "API_Call_Timeout"
        static let sendQueryInitiated = "Send_Query_Initiated"
        static let firstQueryAsked = "FirstQueryAsked"
        static let sendQuery = "Send_Query"
        static let answerShareButtonClicked = "Answer_Share_Button_Clicked"
        static let answerSaveButtonClicked = "Answer_Save_Button_Clicked"
        static let startedPlayingResponseAudio = "Started_Playing_Response_Audio"
        static let stoppedPlayingResponseAudio = "Stopped_Playing_Response_Audio"
        static let sendRecordAudioClickEvent = "Send_Record_Audio_Click_Event"
        static let cancelRecordAudioClickEvent = "Cancel_Record_Audio_Click_Event"
        static let transcriptionSuccess = "Transcription_Success"
        static let transcriptionFailed = "Transcription_Failed"
        static let permissionFallbackDefaultSettingShown = "Permission_Fallback_Default_Setting_Shown"
        static let permissionFallbackDefaultSettingClicked = "Permission_Fallback_Default_Setting_Clicked"
        static let permissionFallbackDefaultSettingCanceled = "Permission_Fallback_Default_Setting_Canceled"
        static let settingsOptionSelected = "Settings_Option_Selected"
        static let logoutClickEvent = "Logout_Click_Event"
        static let faqClicked = "FAQ_Clicked"
        static let newChatClickEvent = "New_Chat_Click_Event"
        static let menuOptionClickEvent = "Menu_Option_Click_Event"
        static let chatHistoryClickEvent = "Chat_History_Click_Event"
        static let accountBenefitScreenProceed = "Account_Benefit_Screen_Proceed"
        static let accountBenefitScreenSkip = "Account_Benefit_Screen_Skip"
        static let mobileVerificationStarted = "Mobile_verification_Started"
        static let sendOTPClickEvent = "Send_OTP_Click_Event"
        static let resendOTPClickEvent = "Resend_OTP_Click_Event"
        static let startOverClicked = "Start_Over_Clicked"
        static let countrySelected = "Country_selected"
        static let loginCompleted = "Login_Completed"
        static let submitOTP = "Submit_OTP"
        static let signupContinueClicked = "Signup_Continue_Clicked"
        static let locationUpdateTriggered = "Location_Update_Triggered"
        static let locationPermissionPromptTriggered = "location_permission_prompt_triggered"
        static let locationPermissionAllowed = "location_permission_allowed"
        static let locationPermissionDeny = "location_permission_deny"
        static let locationFetchSuccess = "location_fetch_success"
        static let locationFetchFailed = "location_fetch_failed"
        static let locationFetchFailedTimeout = "location_fetch_failed_timeout"
        static let forceUpdatePopupShown = "Force_Update_Popup_Shown"
        static let forceUpdatePopupUpdateClicked = "Force_Update_Popup_Update_clicked"
        static let forceUpdatePopupCancelClicked = "Force_Update_Popup_Cancel_clicked"
    }

    // MARK: - Adjust tokens (exact from doc)
    enum AdjustToken {
        static let appInstalled = "981wey"
        static let appUpdated = "a5ivp2"
        static let appOpened = "61k1jl"
        static let screenExited = "23v5xq"
        static let screenViewed = "z3gq3w"
        static let termsOfUseOpened = "7c0wx6"
        static let privacyPolicyOpened = "v5su03"
        static let saveLanguageClick = "gm23vx"
        static let nameSaveClick = "z7kiri"
        static let nameSkipClick = "1vhqtu"
        static let firstTimeDashboardViewed = "wz14hx"
        static let dashboardViewed = "z0hjfd"
        static let cardShown = "w0qnlx"
        static let cardViewed = "yawelk"
        static let cardClicked = "vbdwhl"
        static let hamburgerMenuClicked = "qfs241"
        static let weatherForecastViewed = "p11w2g"
        static let chatIconClicked = "dtokim"
        static let microphoneClickEvent = "18uih3"
        static let imageOptionDialogClickEvent = "rjss82"
        static let permissionPopupShown = "s8oak6"
        static let permissionGranted = "gd65n2"
        static let permissionDenied = "max4sq"
        static let permissionFallbackSettingShown = "xsarfi"
        static let permissionFallbackSettingClicked = "1mxbyr"
        static let permissionFallbackSettingCanceled = "i3tojy"
        static let inputCaptureFailed = "grjv8e"
        static let contentTryAgainClicked = "byfax2"
        static let apiCallInitiated = "jsygs3"
        static let apiCallSuccess = "qmt9a1"
        static let apiCallFailed = "alqyyz"
        static let apiCallTimeout = "vv832c"
        static let sendQueryInitiated = "4gpicl"
        static let firstQueryAsked = "2cm8sd"
        static let sendQuery = "y4rx2e"
        static let answerShareButtonClicked = "wzstz6"
        static let answerSaveButtonClicked = "sikvvk"
        static let startedPlayingResponseAudio = "bxhxht"
        static let stoppedPlayingResponseAudio = "ax8n8c"
        static let sendRecordAudioClickEvent = "pzjy27"
        static let cancelRecordAudioClickEvent = "eydrsn"
        static let transcriptionSuccess = "ha1hza"
        static let transcriptionFailed = "m0948d"
        static let logoutClick = "d7ezu4"
        static let settingsOptionSelected = "j6bp3r"
        static let menuOptionClickEvent = "c5ztkm"
        static let chatHistoryClick = "6tvwdj"
        static let newChatClickEvent = "abjgjz"
        static let accountBenefitScreenProceed = "slxx3d"
        static let accountBenefitScreenSkip = "s6dw2h"
        static let sendOTPClick = "s9fq25"
        static let mobileVerificationStarted = "veossv"
        static let resendOTPClick = "soerz4"
        static let startOverClicked = "xes0d9"
        static let countrySelected = "6sn81s"
        static let loginCompleted = "26zf0i"
        static let submitOTP = "ndzn9b"
        static let signupContinueClicked = "u7ikc1"
        static let faqClicked = "iq2f8o"
        static let locationUpdateTriggered = "i2o7ll"
        static let locationPermissionAllowed = "h0mjgs"
        static let locationPermissionDeny = "emnahq"
        static let locationFetchSuccess = "xomftz"
        static let locationFetchFailed = "glh09r"
        static let locationFetchFailedTimeout = "u48raj"
        static let locationPermissionPromptTriggered = "d8yz2w"
        static let forceUpdatePopupShown = "98ieih"
        static let forceUpdatePopupUpdateClicked = "a5j6xr"
        static let forceUpdatePopupCancelClicked = "uzux2h"
    }

    // MARK: - Property keys (exact from doc)
    enum Property {
        static let screenName = "screen_name"
        static let langaugeCode = "langauge_code"
        static let cardType = "Card_Type"
        static let cardCategory = "Card_category"
        static let imageId = "image_id"
        static let sentenceId = "sentence_id"
        static let text = "Text"
        static let views = "Views"
        static let country = "Country"
        static let state = "State"
        static let assetType = "Asset_Type"
        static let assetName = "Asset_Name"
        static let stage = "Stage"
        static let concern = "Concern"
        static let dateRange = "Date Range"
        static let icon = "Icon"
        static let option = "Option"
        static let permissionType = "Permission_type"
        static let attempt = "Attempt"
        static let inputType = "Input_type"
        static let source = "Source"
        static let failureReason = "Failure_Reason"
        static let apiName = "API_Name"
        static let followupPrompt = "followup_prompt"
        static let imageQuery = "image_query"
        static let textQuery = "text_query"
        static let voiceQuery = "voice_query"
        static let weatherAdviceCta = "weather_advice_cta"
        static let lengthOfAudio = "length_of_audio"
        static let lengthOfTextQuery = "length_of_Text_query"
        static let sizeOfImageKb = "size_of_image_kb"
        static let audioFormat = "audio_format"
        static let type = "type"
        static let clickType = "click_type"
        static let validQuery = "Valid_Query"
        static let clarificationNeededAsset = "clarification_needed_asset"
        static let clarificationNeededConcern = "clarification_needed_concern"
        static let noOfSecondsPlayed = "No_of_seconds_played"
        static let confidenceScore = "Confidence_Score"
        static let optionKey = "option"
        static let value = "value"
        static let question = "Question"
        static let id = "ID"
        static let conversationId = "Conversation ID"
        static let questionIndex = "question_index"
        static let channel = "channel"
        static let trigger = "trigger"
        static let countryCode = "country_code"
        static let userId = "user_id"
        static let isNewUser = "is_new_user"
        static let verificationStatus = "verification_status"
        static let errorMessage = "error_message"
    }

    // MARK: - User attribute keys (exact from doc)
    enum UserAttribute {
        static let id = "ID"
        static let registrationDate = "Registration Date"
        static let appVersion = "App_Version"
        static let versionCode = "Version_Code"
        static let buildVersion = "Build version"
        static let ipCountry = "IP_Country"
        static let ipState = "IP_State"
        static let ipDistrict = "IP_District"
        static let ipBlock = "IP_Block"
        static let ipVillage = "IP_VILLAGE"
        static let ipLocality = "IP_Locality"
        static let gpsCountry = "GPS_Country"
        static let gpsState = "GPS_State"
        static let gpsDistrict = "GPS_District"
        static let gpsBlock = "GPS_Block"
        static let gpsVillage = "GPS_VILLAGE"
        static let gpsLocality = "GPS_Locality"
        static let country = "Country"
        static let state = "State"
        static let district = "District"
        static let block = "Block"
        static let village = "Village"
        static let locality = "Locality"
        static let locale = "Locale"
        static let preferredLanguage = "Preferred language"
        static let name = "Name"
        static let firstName = "First Name"
        static let mobileNoVerified = "Mobile_No_Verified"
        static let phoneNo = "Phone No"
        static let crops = "Crops"
        static let livestock = "Livestock"
        static let gender = "Gender"
        static let role = "Role"
        static let consentGivenForWhatsAppCommunication = "Consent given for WhatsApp communication"
        static let adMobEnabled = "Ad_mob_enabled"
        static let age = "Age"
        static let llmModel = "LLM_Model"
        static let memory = "Memory"
        static let mergedTo = "merged_to"
        static let gpsLocationShared = "GPS Location Shared"
        static let v2ShowNameScreenOnboarding = "v2_show_name_screen_onboarding"
        static let theme = "Theme"
        static let preferredLanguageStringLanguageSettings = "Preferred language String Language settings"
        static let BUILD_VERSION = "BUILD_VERSION"
        static let GENDER = "GENDER"
        static let CROPS = "CROPS"
        static let LIVESTOCK = "LIVESTOCK"
        static let FIRST_NAME = "FIRST_NAME"
        static let NAME = "NAME"
        static let PHONE_NO = "PHONE_NO"
        static let ROLE = "ROLE"
        static let PREFERRED_LANGUAGE = "PREFERRED_LANGUAGE"
        static let CONSENT_WHATSAPP = "CONSENT_WHATSAPP"
        static let AD_MOB_ENABLED = "AD_MOB_ENABLED"
        static let AGE = "AGE"
        static let APP_VERSION = "APP_VERSION"
        static let APP_VERSION_CODE = "APP_VERSION_CODE"
        static let LLM_MODEL = "LLM_MODEL"
        static let MEMORY = "MEMORY"
    }
}
